title: Nemanja Mijailovic's Blog
email: nemanja@mijailovic.net

baseurl: ""
url: "https://mijailovic.net"

github_username: Metalnem
instagram_username: insta_macak
rss: RSS

permalink: /:year/:month/:day/:title/

markdown: kramdown
theme: minima

exclude: [CNAME, Gemfile, LICENSE, README.md]

plugins:
  - jekyll-feed
