title: Nemanja Mijailovic's Blog

baseurl: ""
url: "https://mijailovic.net"
github_username: metalnem

permalink: /:year/:month/:day/:title/

markdown: kramdown
theme: minima

exclude: [CNAME, Gemfile, LICENSE, README.md]
